---
float64 vehicle_mode
float64 navigation_mode
float64 robot_radius
float64 tool_radius
float64 safety_distance
float64 point_spacing
int8 cleanmode
bool enableinsertion
float64 local_origin_longitude
float64 local_origin_latitude
float64 speed_run
float64 speed_max
float64 speed_min
float64 slow_zone1_max
float64 slow_zone2_max
float64 stop_zone_max
float64 left_turn_extension
float64 right_turn_extension
float64 road_width
float64 zone_width
