#node_parameter_mapping.yaml
gnss_converter_by_um982:
  params:
    - ref_latitude
    - ref_longitude
    - ref_height
    - gnss_offset_x
    - gnss_offset_y
  yaml_file: "/home/lyrobot004/LH_GNSS_NAVIGATION_WS/src/gnss_converter_by_um982/config/gnss_converter_by_um982.yaml"

tracked_vehicle_navigation:
  params:
    - lookahead_dist
    - max_velocity
    - min_velocity
    - xy_goal_tolerance
    - xy_middle_tolerance
    - yaw_goal_tolerance
    - wheel_base
    - angular_velocity_limit
    - proportion
    - authorized_hardware_id
  yaml_file: "/home/lyrobot004/robot_communication_ws/src/vehicle_navigation/config/purepursuit_params.yaml"

obstacle_detector:
  params:
    - scan_topic
    - robot_frame
    - map_frame
    - slow_zone1_min
    - slow_zone1_max
    - slow_zone2_min
    - slow_zone2_max
    - stop_zone_max
    - main_lane_width
    - side_lane_width
    - lane_detect_length
    - min_points_threshold
    - authorized_hardware_id
  yaml_file: "/home/lyrobot004/robot_communication_ws/src/laser_obstacle_detector/config/obstacle_detector.yaml"
