/vehicle_navigation_node:
  ros__parameters:
    lookahead_dist: 1.0  #前瞻距离
    max_velocity: 1.0  #最大速度
    min_velocity: -1.0  #最小速度
    xy_goal_tolerance: 0.05  #xy目标点容差
    xy_middle_tolerance: 0.2
    yaw_goal_tolerance: 5.0  #yaw目标点容差
    wheel_base: 1.0  #轴距
    angular_velocity_limit: 0.25  #角速度限制
    proportion: 1.0  #比例系数
    pose_offset_x_: 0.0
    pose_offset_y_: 0.0
    authorized_hardware_id: 'c86dd31a0fc1d8187ebc942407b3dff9'
    
