pcd2pgm:
  ros__parameters:
    pcd_file: $HOME/inHome/pcd/shuobao-pcd/GlobalMap.pcd
    odom_to_lidar_odom: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    flag_pass_through: true
    map_resolution: 0.05
    map_topic_name: preview_pgmmap
    thre_radius: 0.05
    thre_z_max: 2.1
    thre_z_min: -0.2
    thres_point_count: 1
    rotated_pcd_save_path: $HOME/inHome/pcd/shuobao-pcd/GlobalMap.pcd
    map_save_path: $HOME/inHome/maps/shuobao-pgm/setting
    map_save_name: map